sudo: false
language: node_js
node_js:
- "node"
cache: yarn
before_script: "node guard.js"
script: "yarn test -- --coverage && yarn lint"
after_script: "yarn coveralls"
before_install: "bash yarn.sh"
notifications:
  email: false
