sudo: false
language: node_js
node_js:
- "node"
cache: yarn
before_script: "TRAVIS_PULL_REQUEST_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH node guard.js"
script: "yarn test -- --coverage && yarn lint"
after_script: "yarn coveralls"
after_success:
  - bash yarn.sh
notifications:
  email: false
