version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint

      - run: yarn test --coverage

      - run: yarn coveralls

      - run: yarn semantic-release || true

      - run: |
        if [[ $CIRCLE_BRANCH == master ]]; then
          yarn deploy-storybook
        fi
